import assert from "node:assert/strict";
import test from "node:test";
import { crc32 } from "node:zlib";
import { columnIndexFromRef, readWorkbook, WorkbookReadError } from "./xlsx-reader.mjs";

/**
 * Build a .xlsx from literal XML parts, stored uncompressed.
 *
 * The fixture is authored as XML rather than committed as a binary because the whole
 * point of these tests is the exact XML constructs Excel emits. A binary blob hides
 * them, and a blob generated by another spreadsheet library would only pin that
 * library's habits. Stored entries keep the writer to a few lines; the reader handles
 * both stored and deflated members and reads the local header either way.
 */
function buildXlsx(parts) {
  const entries = [];
  const chunks = [];
  let offset = 0;

  for (const [name, xml] of Object.entries(parts)) {
    const nameBytes = Buffer.from(name, "utf8");
    const data = Buffer.from(xml, "utf8");
    const checksum = crc32(data);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt32LE(checksum, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBytes.length, 26);

    entries.push({ name: nameBytes, checksum, size: data.length, offset });
    chunks.push(local, nameBytes, data);
    offset += local.length + nameBytes.length + data.length;
  }

  const directory = [];
  let directorySize = 0;
  for (const entry of entries) {
    const header = Buffer.alloc(46);
    header.writeUInt32LE(0x02014b50, 0);
    header.writeUInt16LE(20, 4);
    header.writeUInt16LE(20, 6);
    header.writeUInt32LE(entry.checksum, 16);
    header.writeUInt32LE(entry.size, 20);
    header.writeUInt32LE(entry.size, 24);
    header.writeUInt16LE(entry.name.length, 28);
    header.writeUInt32LE(entry.offset, 42);
    directory.push(header, entry.name);
    directorySize += header.length + entry.name.length;
  }

  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(directorySize, 12);
  end.writeUInt32LE(offset, 16);

  return Buffer.concat([...chunks, ...directory, end]);
}

const SHARED_STRINGS = `<?xml version="1.0" encoding="UTF-8"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="9" uniqueCount="9">
  <si><t>Programme: Widget Foundations</t></si>
  <si><t>Project</t></si>
  <si><t>Task</t></si>
  <si><t>W1. FIRST GROUP</t></si>
  <si><t xml:space="preserve">Pick the </t><r><t>widget</t></r><r><t xml:space="preserve"> size</t></r></si>
  <si><t>Ampersand &amp; &lt;angle&gt; &quot;quoted&quot; &#65;&#x42;</t></si>
  <si><t>Order the widgets</t></si>
  <si/>
  <si><t>W2. SECOND GROUP</t></si>
</sst>`;

/**
 * Row 1 is a styled banner with no cells, and B2/C2 are styled-but-empty. Both are the
 * self-closing form Excel actually writes, and both previously swallowed the following
 * element. Row 4 is skipped entirely, and row 6 skips column B, so gap-filling is
 * exercised in both directions.
 */
const SHEET_ONE = `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row r="1" spans="1:5" ht="44.1" customHeight="1"/>
    <row r="2" spans="1:5"><c r="A2" t="s"><v>0</v></c><c r="B2" s="70"/><c r="C2" s="70"/></row>
    <row r="3" spans="1:5"><c r="A3" t="s"><v>1</v></c><c r="B3" t="s"><v>2</v></c></row>
    <row r="5" spans="1:5"><c r="A5" t="s"><v>3</v></c><c r="B5"><v>1</v></c><c r="C5" t="s"><v>4</v></c><c r="D5" t="s"><v>5</v></c></row>
    <row r="6" spans="1:5"><c r="A6" s="70"/><c r="C6" t="s"><v>6</v></c></row>
    <row r="7" spans="1:5"><c r="A7" t="s"><v>8</v></c><c r="B7" t="inlineStr"><is><t>inline value</t></is></c><c r="C7" t="s"><v>7</v></c></row>
  </sheetData>
</worksheet>`;

const SHEET_TWO = `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>second sheet</t></is></c></row></sheetData>
</worksheet>`;

/**
 * The relationship targets are deliberately crossed: the first tab resolves to
 * sheet9.xml and the second to sheet2.xml. Part-file numbering carries no meaning, and
 * a reader that assumes tab order matches sheetN.xml order reads the wrong tab.
 */
const WORKBOOK = `<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="Widget Programme" sheetId="4" r:id="rId7"/>
    <sheet name="Notes &amp; Extras" sheetId="1" r:id="rId3"/>
  </sheets>
</workbook>`;

const RELS = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>
  <Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet9.xml"/>
  <Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
</Relationships>`;

function sampleWorkbook(overrides = {}) {
  return buildXlsx({
    "xl/workbook.xml": WORKBOOK,
    "xl/_rels/workbook.xml.rels": RELS,
    "xl/sharedStrings.xml": SHARED_STRINGS,
    "xl/worksheets/sheet9.xml": SHEET_ONE,
    "xl/worksheets/sheet2.xml": SHEET_TWO,
    ...overrides,
  });
}

function sheetRows() {
  return readWorkbook(sampleWorkbook()).sheets.get("Widget Programme");
}

test("a styled empty row does not swallow the row beneath it", () => {
  const rows = sheetRows();
  // Row 1 is the self-closing banner. Its content must stay empty, and row 2's
  // heading must stay on row 2 rather than being pulled up into it.
  assert.deepEqual(rows[0], ["", "", "", ""]);
  assert.equal(rows[1][0], "Programme: Widget Foundations");
});

test("a styled empty cell does not swallow the cell beside it", () => {
  const rows = sheetRows();
  // A6 is styled-but-empty and C6 carries the task, so a swallowed A6 shows up as the
  // task text sliding into the project column.
  assert.equal(rows[5][0], "");
  assert.equal(rows[5][2], "Order the widgets");
});

test("keeps every row on its declared row number, including skipped rows", () => {
  const rows = sheetRows();
  assert.equal(rows[2][0], "Project");
  assert.equal(rows[2][1], "Task");
  // Row 4 is absent from the XML and must still occupy its own slot.
  assert.deepEqual(rows[3], ["", "", "", ""]);
  assert.equal(rows[4][0], "W1. FIRST GROUP");
});

test("joins the runs of a split string and preserves their spacing", () => {
  assert.equal(sheetRows()[4][2], "Pick the widget size");
});

test("decodes named and numeric XML entities", () => {
  assert.equal(sheetRows()[4][3], 'Ampersand & <angle> "quoted" AB');
});

test("reads numeric and inline-string cells", () => {
  const rows = sheetRows();
  assert.equal(rows[4][1], "1");
  assert.equal(rows[6][1], "inline value");
});

test("an empty shared string reads as empty rather than undefined", () => {
  assert.equal(sheetRows()[6][2], "");
});

test("resolves sheets through the relationships, not the part-file numbering", () => {
  const workbook = readWorkbook(sampleWorkbook());
  assert.deepEqual(workbook.sheetNames, ["Widget Programme", "Notes & Extras"]);
  // "Widget Programme" is the first tab but lives in sheet9.xml.
  assert.equal(workbook.sheets.get("Notes & Extras")[0][0], "second sheet");
});

test("rows are padded to a consistent width", () => {
  const rows = sheetRows();
  const widths = new Set(rows.map((row) => row.length));
  assert.equal(widths.size, 1, `expected one row width, saw ${[...widths].join(", ")}`);
});

test("columnIndexFromRef handles multi-letter columns", () => {
  assert.equal(columnIndexFromRef("A1"), 0);
  assert.equal(columnIndexFromRef("E13"), 4);
  assert.equal(columnIndexFromRef("Z9"), 25);
  assert.equal(columnIndexFromRef("AA1"), 26);
  assert.equal(columnIndexFromRef("BC7"), 54);
});

test("refuses a file that is not a zip instead of returning empty sheets", () => {
  const placeholder = Buffer.from("This OneDrive file has not downloaded yet.", "utf8");
  assert.throws(() => readWorkbook(placeholder), WorkbookReadError);
  assert.throws(() => readWorkbook(Buffer.alloc(0)), WorkbookReadError);
});

test("refuses a workbook with no sheet index instead of guessing", () => {
  const withoutRels = buildXlsx({
    "xl/workbook.xml": WORKBOOK,
    "xl/sharedStrings.xml": SHARED_STRINGS,
    "xl/worksheets/sheet9.xml": SHEET_ONE,
  });
  assert.throws(() => readWorkbook(withoutRels), WorkbookReadError);
});
